### ISSUE TITLE
AGU24

### ISSUE THREAD

**Issue by CherrelleTucker** [NASA-IMPACT/snwg-sep#49]
### Ultimate Goal

Promote the SNWG as a whole and SNWG-facilitated solutions in particular to the AGU (American Geophysical Union) community. 

### Audience

Solution end users within the governmental and academic scientific communities 

### Additional Context

"AGU 2024 is 9-13th December in Washington DC and the theme this year is What’s Next for Science. We have organized the following session, Timely Decision-Making with Near Real-Time & Low Latency Earth Data Products: Tools and User Stories, and invite you to submit an abstract for this session." 
What do you think of a presentation of impact stories related to the SNWG NRT solutions? I'm thinking primarily on the TEMPO, ICESat quicklooks, and the low latency HLS solutions.

------

12/9/24-12/13/24	Washington, DC	Conference	
Abstract/proposal due: 4/24/2024	
Final submission deadline: 7/31/2024	[https://www.agu.org/annual-meeting](https://www.agu.org/annual-meeting)

### Related Issues or files

```[tasklist]
### Tasks
- [ ] https://github.com/NASA-IMPACT/snwg-sep/issues/53
- [x] Submit abstracts by July 31, 2024
- [ ] Print: SNWG Fact sheets
- [ ] Print: bookmarks
- [ ] Print: SNWG MO stickers
- [ ] https://github.com/NASA-IMPACT/snwg-sep/issues/41
- [ ] https://github.com/NASA-IMPACT/snwg-sep/issues/71
```

![Image](https://github.com/NASA-IMPACT/snwg-sep/assets/106271365/17e6d502-3166-4994-9e1d-c5dcde282e30)

**Comment by CherrelleTucker** [comment]
Katrina: Will we have user stories relating to those solutions in time for December?  So far we don't have any for ICESat-2; TEMPO NRT won't be operational for another year; and low latency HLS will still be in formulation.

Pontus: Well, it would be more about science and applications enabled by these solutions rather than any operational user stories. For TEMPO NRT, we could talk about early-adopters and the proposed use by the forest service. To be honest, my primary interests in this are the strategical/political aspects (HQ, Earth Action, Tom and Karen, etc.) of a presentation focusing on impact and usage of SNWG solutions.

Natasha: I'm one of the conveners for that session! We could definitely propose, I think you're right Pontus that it's good optics. Maybe we could work with Aaron Naeger to focus in on TEMPO in particular since he has such an active Early Adopter community. The goal of the session is to get folks together to share about NRT data and learn about new NRT data. We should think about how it might coordinate with (or not) our Town Hall too.


Natasha Sadoff: [https://agu.confex.com/agu/agu24/prelim.cgi/Session/224836](https://agu.confex.com/agu/agu24/prelim.cgi/Session/224836) AGU is good to discuss even more broadly - if anyone is searching for other good opportunities to submit an abstract on solutions in particular - and if/how we can encourage our implementation teams to present (if they're ready, etc.).

Pontus: FWIW, I'm co-convener of this sessions: [https://agu.confex.com/agu/agu24/prelim.cgi/Session/228797](https://agu.confex.com/agu/agu24/prelim.cgi/Session/228797)

**Comment by CherrelleTucker** [comment]
[AGU Brainstorm Doc](https://docs.google.com/document/d/14RLI_m5zBa2bLth4kIsj44XV0rvlmraAJdGf6guF7ws/edit)

**Comment by CherrelleTucker** [comment]
Infographic is waiting for approval from USGEO group to use. 
Update back of bookmark to include 2022 solutions. 
Rachel to tag up with Katrina about what to update the back of bookmark

Rachel and Pontus have worked on Townhall flyer. Aries Keck (a person) has responded to Rachel. Are still discussing a review workflow for anything that is sent to them. Once Aries Keck replies, we will be able to move forward with flyer. 

Natasha asked Aries about the logo. They want to have an exploratory conversation with Natasha. Unlikely to have a definitive answer soon. Invite Pontus, Rachel. Natasha will set up that meeting.

**Comment by CherrelleTucker** [comment]
[2024-08-29  SNWG SEP Weekly Meeting](https://docs.google.com/document/d/1DWR2XClGZ4zPvOgFkAuQNKArVDjvqmBDGA3OYNpBcTI/edit)
 
- Action: AGU - Plan to print the SNWG Infographic as well and the SNWG bookmark
- Action: Check for which updates need to be made to the solutions listed on the back of the bookmark
- Could think about doing a SNWG MO sticker
  -  Action: See if Rachel could add text (spell out acronym) on the sticker logo

**Comment by CherrelleTucker** [comment]
Natasha Sadoff
  8:50 AM (Slack)
 I made a formal request with HQ Comms (there are webforms now) for AGU booth space and a hyperwall talk for SNWG. Will keep you all posted on the outcome and if we're approved!

**Comment by rwyatt19** [comment]
@kvirts Here are [pngs of the revised bookmark](https://drive.google.com/drive/folders/1BafSQl0urxZNemH0OmEQPz-g7wLrN-7c?usp=sharing) with updated solutions on the back. What about the "tagline" on the front? (Delivering High-Profile Satellite Observation Solutions) Are we good with that as-is, or do we want to wait and see what comes out of [this discussion](https://github.com/NASA-IMPACT/snwg-sep/issues/61)?

**Comment by kvirts** [comment]
Thanks @rwyatt19, this looks great!  You make a good point on the tagline--let's hold off finalizing for a while since that is currently being discussed.
